using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Miner.Interop.Process
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.237
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    //
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    //
    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class EdmRepository
    {
        #region Fields

        private EdmTable compatibleUnitField;
        private EdmTable designField;
        private string typeField;
        private EdmTable workLocationField;
        private EdmTable workRequestField;

        #endregion

        #region Constructors

        /// <summary>
        ///     Initializes a new instance of the <see cref="EdmRepository" /> class.
        /// </summary>
        public EdmRepository()
        {
            this.typeField = "2";
        }

        #endregion

        #region Public Properties

        /// <summary>
        ///     Gets or sets the compatible unit.
        /// </summary>
        /// <value>
        ///     The compatible unit.
        /// </value>
        public EdmTable CompatibleUnit
        {
            get { return this.compatibleUnitField; }
            set { this.compatibleUnitField = value; }
        }

        /// <summary>
        ///     Gets or sets the design.
        /// </summary>
        /// <value>
        ///     The design.
        /// </value>
        public EdmTable Design
        {
            get { return this.designField; }
            set { this.designField = value; }
        }

        /// <summary>
        ///     Gets or sets the type.
        /// </summary>
        /// <value>
        ///     The type.
        /// </value>
        [XmlAttribute]
        [DefaultValue("2")]
        public string Type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <summary>
        ///     Gets or sets the work location.
        /// </summary>
        /// <value>
        ///     The work location.
        /// </value>
        public EdmTable WorkLocation
        {
            get { return this.workLocationField; }
            set { this.workLocationField = value; }
        }

        /// <summary>
        ///     Gets or sets the work request.
        /// </summary>
        /// <value>
        ///     The work request.
        /// </value>
        public EdmTable WorkRequest
        {
            get { return this.workRequestField; }
            set { this.workRequestField = value; }
        }

        #endregion
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class EdmField
    {
        #region Fields

        private string nameField;

        #endregion

        #region Public Properties

        /// <summary>
        ///     Gets or sets the name.
        /// </summary>
        /// <value>
        ///     The name.
        /// </value>
        [XmlAttribute]
        public string Name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        #endregion
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public partial class EdmTable
    {
        #region Fields

        private EdmField[] fieldsField;
        private string tableNameField;

        #endregion

        #region Public Properties

        /// <summary>
        ///     Gets or sets the fields.
        /// </summary>
        /// <value>
        ///     The fields.
        /// </value>
        [XmlArrayItem("Field", IsNullable = false)]
        public EdmField[] Fields
        {
            get { return this.fieldsField; }
            set { this.fieldsField = value; }
        }

        /// <summary>
        ///     Gets or sets the name of the table.
        /// </summary>
        /// <value>
        ///     The name of the table.
        /// </value>
        [XmlAttribute]
        public string TableName
        {
            get { return this.tableNameField; }
            set { this.tableNameField = value; }
        }

        #endregion
    }
}