//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the NuGet Package and includes
// 	   configurations that are used by the Apache Logging Framework.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
[assembly: log4net.Config.XmlConfigurator(ConfigFile = "Wave.log4net.config", Watch = true)]